# Continuous Integration workflow for GitHub Actions
name: CI
on:
  push:
    branches:
      - main
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install
        poetry run gbfs2osm --help

    - name: Run end-to-end tests
      run: |
        # Bixi Montréal
        poetry run gbfs2osm --gbfs-feed-url https://gbfs.velobixi.com/gbfs/2-2/gbfs.json --output-file output_bixi.osm --operator Bixi --network Bixi --use-short-name-for-station-id --network-wikidata-id Q386 --operator-wikidata-id Q386
        # Bike Share Toronto
        poetry run gbfs2osm --gbfs-feed-url https://tor.publicbikesystem.net/ube/gbfs/v1/gbfs.json --output-file output_bikesharetoronto.osm --operator "Bike Share Toronto" --network bike_share_toronto
        poetry run gbfs2osm --gbfs-feed-url https://quebec.publicbikesystem.net/customer/ube/gbfs/v1/gbfs.json --output-file output_avelo.osm --operator "Réseau de transport de la Capitale" --network a_velo